# Generated by Django 5.0.7 on 2024-07-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyhistory',
            old_name='completed_date',
            new_name='completed_on',
        ),
        migrations.RenameField(
            model_name='studyhistory',
            old_name='goal',
            new_name='group_name',
        ),
        migrations.AddField(
            model_name='studyhistory',
            name='details',
            field=models.TextField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
