# Generated by Django 5.0.7 on 2024-07-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studyhistory_goal_alter_studygroup_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='71124154a75d4be79d8d6bc478bea1f2', max_length=255, unique=True),
        ),
    ]
