# Generated by Django 5.0.7 on 2024-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studygroup_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='f26691580eb444ec99bee26eed416257', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studyhistory',
            name='group_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
