# Generated by Django 5.0.7 on 2024-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_studygroup_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='f8f85e837be742a2a34cc9a7c6484d26', max_length=255, unique=True),
        ),
    ]
