# Generated by Django 5.0.7 on 2024-07-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_studygroup_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='9a8ae75efe944919a35f837d03bf1796', max_length=255, unique=True),
        ),
    ]
