# Generated by Django 5.0.7 on 2024-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_studygroup_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='05a8b12dc24d48308805042d878c1657', max_length=255, unique=True),
        ),
    ]
