# Generated by Django 5.0.7 on 2024-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_studygroup_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='cf670aa663e24f409dc8ea607c7ae158', max_length=255, unique=True),
        ),
    ]
