# Generated by Django 5.0.7 on 2024-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_studygroup_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='end_time',
            field=models.DateTimeField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='c6fea6d3', max_length=8, unique=True),
        ),
    ]
