# Generated by Django 5.0.7 on 2024-07-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studygroup_end_time_studygroup_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='room_number',
            field=models.CharField(default='4038f5d5', max_length=8, unique=True),
        ),
    ]
